name: App
favicon: null
layout_spectrum: 0.41808835603296757
typography_spectrum: 0.14754801662638783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.21131612919270992
  lightness: 0.8465019562281668
  saturation: 0.39149574958719313
  rhythmicContrast: 0.8832494034431875
purpose: []
